### ISSUE TITLE
Corr Test

### ISSUE THREAD

**Issue by mucun1988** [AlexGrinch/ro_sgns#3]
Dear Alex

I am trying to run the correlation test. 

Based on your datasets_corr function in functions.py, I am doing something as follows
```
opt_experiment(model_enwik,
               mode='PS', 
               d=100,
               eta = 5e-5, # step size
               MAX_ITER=7,
               from_iter=0,
               start_from='SVD',
               init=(True, C_svd, W_svd))

from scipy.spatial.distance import cosine
from scipy.stats import spearmanr

datasets_path = ".\datasets"
indices = np.load(open(datasets_path+'/indices.npz', 'rb'))
name = 'wordsim_sim'

pairs_num = indices['0'+name].size
idx = np.arange(pairs_num)
        
ind1 = indices['0'+name][idx]
ind2 = indices['1'+name][idx]
scores = indices['2'+name][idx]

W, C = model_enwik.W, model_enwik.C
G = W
G = G / np.linalg.norm(G, axis=0)
cosines = (G[:,ind1]*G[:,ind2]).sum(axis=0)
spearmanr(cosines, scores)[0]```

The code works find, but the result is -0.11981128713175491, which I expect to be 0.729 in the paper. I am pretty sure I misunderstand something and code something wrong.

Could you please help to take a look at what is going wrong?


Thanks,
Matt

**Comment by AlexGrinch** [comment]
Hi Matt,
I can not understand what's going on, it seems that your code does exactly the same thing we did in the experiments. Maybe there is a problem in indices mismatch? If the word order in your W matrix differs from the word order in our experiments, you are just measuring correlations between random pairs of words (and correlation -0.12 seems pretty close to something completely random).

If the problem is indices mismatch, you should change indices in a way to make them correspondent. I am sorry, I was working on this code more than a year ago (and when I look at it now, it seems completely unfamiliar :D), but I managed to find a script responsible for indices.npz creation.

    import os
    names = []
    arrs = []
    for filename in os.listdir('datasets'):
    
    if filename[-4:]=='.csv':

        name = filename[:-4]
        for i in xrange(3):
            names.append(str(i)+name)
        
        dataset = pd.read_csv('datasets/'+filename, header=None, delimiter=';').values
        ind1 = []
        ind2 = []
        vec2 = []
        model_dict=model_enwik.dictionary
        for i in xrange(dataset.shape[0]):
            word1 = dataset[i, 0].lower()
            word2 = dataset[i, 1].lower()
            if (word1 in model_dict and word2 in model_dict):
                ind1.append(int(model_dict[word1]))
                ind2.append(int(model_dict[word2]))
                vec2.append(np.float64(dataset[i, 2]))
                
        ind1 = np.array(ind1)
        ind2 = np.array(ind2)
        vec2 = np.array(vec2)
        
        arrs.append(ind1)
        arrs.append(ind2)
        arrs.append(vec2)

    np.savez(open('datasets/indices.npz', 'wb'), **{name:value for name,value in zip(names, arrs)})

Please, take a look at it and make sure that you are measuring correlations between corresponding words. 

Looking forward to your reply!

Best,
Aleksey

**Comment by mucun1988** [comment]
Dear Alex,

Will have a try shortly!

Thanks,
Matt

**Comment by mucun1988** [comment]
Dear Alex


It solves my problem! You are right! 

Based on the code you posted, the following is what works out from my side.
```
filename = 'wordsim_sim.csv'
dataset = pd.read_csv('datasets/'+filename, header=None, delimiter=';').values
ind1 = []
ind2 = []
vec2 = []
model_dict=model_enwik.vocab
for i in xrange(dataset.shape[0]):
    word1 = dataset[i, 0].lower()
    word2 = dataset[i, 1].lower()
    if (word1 in model_dict and word2 in model_dict):
        ind1.append(int(model_dict[word1]))
        ind2.append(int(model_dict[word2]))
        vec2.append(np.float64(dataset[i, 2]))
ind1 = np.array(ind1)
ind2 = np.array(ind2)
vec2 = np.array(vec2)
cosines = (G[:,ind1]*G[:,ind2]).sum(axis=0)
spearmanr(cosines, scores)[0]
```

The output is 0.726, which looks great!


Many thanks,
Matt

**Comment by YerongLi** [comment]
Hi, do you have the full script for the evaluation, I am I reproduced the indices file and after using your final script, I get a correlation score 0.49 at iteration 7.

BTW, did you get the **model_enwik.vocab** from **model_enwik.load_matrices()**? from the original code? @mucun1988 

Actually I found in the **data_to_matrices()** function

```
    ########################## Data to Matrices ###########################
    
    def data_to_matrices(self, sentences, r, k, to_file):
        """
        Process raw sentences, create word dictionary, matrix D and matrix B
        then save them to file.
        """
        
        self.vocab = self.create_vocabulary(sentences, r)
        self.D = self.create_matrix_D(sentences)
        self.B = self.create_matrix_B(k)
        
        sorted_vocab = sorted(self.vocab.items(), key=operator.itemgetter(1))
        vocab_to_save = np.array([item[0] for item in sorted_vocab])
        
        np.savez(open(to_file, 'wb'), vocab=vocab_to_save, D=self.D, B=self.B)
```
with `np.savez(open(to_file, 'wb'), vocab=vocab_to_save, D=self.D, B=self.B)` one cannot retrieve **vocab** correctly later with **load_matrices()**.

That's why I keep the vocab in a seperate file:
[indices9.txt](https://github.com/AlexGrinch/ro_sgns/files/2224617/indices9.txt)

**Comment by YerongLi** [comment]
For example, here is the evolution of correlation scores I've got.
![pmm_enwik9](https://user-images.githubusercontent.com/13112023/43155948-71ef785a-8f3e-11e8-8aee-0174d85dbe01.png)
